src/Entity/Reservation.php
<?php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Room;
    /**
     * @ORM\Column(type="date")
     */
    private $DateStart;
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateEnd;
    private $Length;
    private $Price;
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getUser(): ?User
    {
        return $this->User;
    }
    public function setUser(?User $User): self
    {
        $this->User = $User;
        return $this;
    }
    public function getRoom(): ?Room
    {
        return $this->Room;
    }
    public function setRoom(?Room $Room): self
    {
        $this->Room = $Room;
        return $this;
    }
    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->DateStart;
    }
    public function setDateStart(\DateTimeInterface $DateStart): self
    {
        $this->DateStart = $DateStart;
        return $this;
    }
    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->DateEnd;
    }
    public function setDateEnd(?\DateTimeInterface $DateEnd): self
    {
        $this->DateEnd = $DateEnd;
        return $this;
    }
    public function getLength(): ?string
    {
        $this->length = date_diff($this->DateEnd, $this->DateStart);
        return $this->length->format('%d');
    }
    public function getPrice(): ?string
    {
        $this->price = $this->length->format('%d') * 20;
        return $this->price;
    }
}

src/Controller/ReservationController.php
<?php
namespace App\Controller;
use App\Entity\Reservation;
use App\Form\Reservation1Type;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 * @Route("/admin/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $this->render('reservation/index.html.twig', [
                'reservations' => $reservationRepository->findAll(),
            ]);
        }
        else {
            $User = $this->get('security.token_storage')
                ->getToken()
                ->getUser();
            $this->get('doctrine')
                ->getManager()
                ->getRepository('App:Reservation')
                ->findByUser($User);
            
            return $this->render('reservation/index.html.twig', [
                'reservations' => $reservationRepository->findByUser($User),
            ]);
        }
    }
    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();
            return $this->redirectToRoute('reservation_index');
        }
        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }
    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('reservation_index', [
                'id' => $reservation->getId(),
            ]);
        }
        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }
        return $this->redirectToRoute('reservation_index');
    }
    /**
     * @Route("/search", name="reservation_search", methods={"GET","POST"})
     */
    public function search(Request $request): Response
    {
        
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    {% if is_granted("ROLE_ADMIN") %}
        <h1>Reservation index</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>DateStart</th>
                    <th>DateEnd</th>
                    <th>User</th>
                    <th>Room</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.user }}</td>
                    <td>{{ reservation.room }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('reservation_new') }}">Create new</a>
    {% elseif is_granted("ROLE_USER") %}
        <h1>Your reservations</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>DateStart</th>
                    <th>DateEnd</th>
                    <th>User</th>
                    <th>Room</th>
                    <th>Length</th>
                    <th>Price</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.user }}</td>
                    <td>{{ reservation.room }}</td>
                    <td>{{ reservation.length }} days</td>
                    <td>&euro; {{ reservation.price }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('reservation_new') }}">Create new</a>
    {% else %}
        <p>Please log in</p>
    {% endif %}
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>DateStart</th>
                <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>DateEnd</th>
                <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}